# Default target â€” override with: cargo +esp build --target xtensa-esp32-espidf
[build]
target = "xtensa-esp32s3-espidf"

[target.xtensa-esp32s3-espidf]
linker = "ldproxy"

[target.xtensa-esp32-espidf]
linker = "ldproxy"

[unstable]
build-std = ["std", "panic_abort"]

[env]
# Workaround for https://github.com/esp-rs/esp-idf-template/issues/174
ESP_IDF_VERSION = "v5.3.2"
