[build]
target = "xtensa-esp32s3-espidf"

[target.xtensa-esp32s3-espidf]
linker = "ldproxy"
# runner = "espflash flash --monitor"

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU = "esp32s3"
# Workaround for https://github.com/esp-rs/esp-idf-template/issues/174
ESP_IDF_VERSION = "v5.3.2"
